// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rltxljroturlhoqsyqpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdHhsanJvdHVybGhvcXN5cXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDA5NjAsImV4cCI6MjA2MDMxNjk2MH0.rhMVuO0vy0KBcLjV-8VIeCzmnc22TnmHszsky-8l8T0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);